# -*- coding: utf-8 -*-
# Chapter 2: map, timeline, links, recall, traps, quiz, cards, skeletons

PRIORITY = 'High'

MAP = ('Major powers and India', [
    ('Major powers', [('Definition', 'capability + intent to shape order'), ('Responses', 'balance, bandwagon, autonomy'), ('US', 'leadership; Quad, CHIPS, dollar'), ('China', 'Middle Kingdom; BRI, A2/AD'), ('Russia', 'Eurasia; energy, nuclear')]),
    ('Rivalries', [('US-China', 'Thucydides Trap; tech; Taiwan'), ('Russia-West', 'NATO; sanctions; energy'), ('Not new Cold War', 'interdependence continues'), ('Impact on India', 'IOR, LAC, chains, autonomy')]),
    ('India’s approach', [('Frame', 'autonomy, multi-alignment'), ('Jaishankar', 'engage, manage, cultivate'), ('US', 'tech, defence, Indo-Pacific'), ('Russia', 'defence, energy, Eurasia')]),
    ('India-China', [('Nature', 'competition + interdependence'), ('Border', '3,488 km; 3 sectors'), ('4 issue boxes', 'Pak nexus; pearls; river; magnets'), ('Close', 'Three Mutuals')]),
    ('India-US', [('Nature', 'partnership, not alliance'), ('Convergence', 'Quad, iCET, Mission 500'), ('Divergence', 'Russia, tariffs, H-1B, Pak'), ('Manage', 'seeks vs avoids')]),
    ('India-Russia', [('Anchor', 'defence + energy'), ('Convergence', 'Kudankulam; INSTC; BRICS'), ('Divergence', 'China; S-400; trade gap'), ('Close', 'diversify the partnership')]),
    ('Europe and France', [('EU', 'FTA 2026; TTC; CBAM'), ('Divergence', 'regulation; Ukraine'), ('France', 'Rafale; Scorpene; Horizon 2047')]),
    ('Japan and Australia', [('Japan', 'ODA to strategy; JPY 10 tn'), ('Gaps', 'execution; CEPA; tech transfer'), ('Australia', 'minerals; PACTS; CECA')]),
])

TIMELINE = [
    ('1947', 'India-USSR diplomatic relations established', False),
    ('1949-50', 'India recognises the PRC (1949); diplomatic relations (1950)', False),
    ('1954', 'Panchsheel Agreement with China', True),
    ('1960s', 'MiG-21 co-production (India-Soviet defence partnership)', False),
    ('1962', 'India-China war: Aksai Chin comes under Chinese control; brief US support', True),
    ('1971', 'India-USSR Treaty of Peace, Friendship and Cooperation; US tilt to Pakistan', True),
    ('1975', 'Aryabhata launched with Soviet help', False),
    ('1976-88', 'India-China ambassadors resume; Rajiv Gandhi visit 1988', False),
    ('1988', 'Kudankulam agreement with the USSR', False),
    ('1993-96', 'India-China peace and tranquillity agreements', False),
    ('1998', 'Pokhran-II sanctions; Jaswant Singh-Strobe Talbott dialogue begins', False),
    ('2000', 'India-Russia Strategic Partnership', False),
    ('2003', 'India-China Special Representatives mechanism', False),
    ('2004', 'India-EU Strategic Partnership', False),
    ('2005', 'India-China agreement on guiding principles for a settlement', False),
    ('2005-08', 'India-US Civil Nuclear Agreement (2008 foundation)', True),
    ('2010', 'India-Russia Special and Privileged Strategic Partnership', False),
    ('2013', 'India-EU FTA talks slow down', False),
    ('2015', 'International Solar Alliance launched (India-France)', False),
    ('2016', 'LEMOA; India designated a Major Defence Partner', False),
    ('2017', 'Doklam standoff', True),
    ('2018', '2+2 Ministerial Dialogue (India-US)', False),
    ('2019', 'US removes India from GSP', False),
    ('2020', 'Galwan clash; BECA', True),
    ('2021', 'First India-Russia 2+2; India-EU Connectivity Partnership', False),
    ('2022', 'Russia invades Ukraine; India-EU TTC announced', False),
    ('2023', 'Finland joins NATO; India joins Artemis Accords; Horizon 2047 (France); Saudi-Iran rapprochement', False),
    ('2024', 'Sweden joins NATO; Depsang-Demchok understanding (October); France accepts UPI (Eiffel Tower tickets)', True),
    ('Apr 2025', 'China licenses seven heavy rare earths; Rafale-M contract', False),
    ('2025', 'Dalai Lama succession statement (July); India-EFTA TEPA; Justice Mission 2025', False),
    ('Jan 2026', 'EU Regulation to phase out Russian gas and LNG', False),
    ('Feb 2026', 'India-France relationship elevated to a Special Global Strategic Partnership', False),
    ('2026', 'India-EU FTA negotiations concluded; Graham Act; US-India interim trade deal (18%); US exits Paris Agreement; Ankara NATO Summit (€70 bn); 18th BRICS Summit; New Delhi Declaration', True),
    ('Sep 2026', 'Trump-Xi summit: AI dialogue proposed, trade truce extended, $30 bn tariff cuts each way', False),
]

LINKS = [
    ('Chapter 1: six phases', 'Phases 5 and 6 (US-China rivalry, Russia-West) are unpacked here with each power’s ambitions and instruments.'),
    ('Chapter 1: India’s evolution', 'The 1971 Treaty and the USS Enterprise episode link to “strategic mistrust” (US) and “strategic trust” (Russia) here.'),
    ('Chapter 1: trade-offs', 'Strategic autonomy versus alignment, China competition versus engagement: the examples are the Quad, Russian oil and S-400 here.'),
    ('Syllabus: India and its neighbourhood', 'China-Pakistan nexus, CPEC, Gwadar, Hambantota and Kyaukpyu, Brahmaputra and Bangladesh lead to the neighbourhood chapters.'),
    ('Syllabus: groupings', 'Quad, BRICS, SCO, I2U2, IMEC, IPEF, AUKUS, RIC and EAEU appear across the powers. Each is a “bilateral, regional and global grouping”.'),
    ('Syllabus: diaspora', 'US diaspora (1.5%, over $300 bn in federal taxes, 82% STEM students) leads to the diaspora topic.'),
    ('Syllabus: policies of other countries', 'US tariffs, the Graham Act 2026, CAATSA, H-1B, China’s rare-earth licensing and EU CBAM are the “effect of policies on India’s interests”.'),
    ('Syllabus: international institutions', 'UNSC and WTO reform, NDB, AIIB, BRICS and SCO platforms.'),
]

RECALL = [
    '**Major power:** capability + intent to shape order. Responses: balancing, bandwagoning, strategic autonomy. Bandwagoning examples: Belarus-Russia, Pakistan-China.',
    '**US:** four ambitions (great-power balance; economic and technological superiority; financial and institutional influence; Western Hemisphere). Quad, I2U2, AUKUS; CHIPS 2022; Graham Act 2026 (up to 100%); Monroe Doctrine; Operation Absolute Resolve.',
    '**China:** national rejuvenation; regional centrality (BRI, CPEC, Gwadar, Djibouti, Two-Ocean, A2/AD); tech leadership (Made in China 2025, New Three); multipolarity (BRICS, SCO, AIIB, GDI, GSI, GCI; Saudi-Iran 2023).',
    '**Russia:** multipolarity (BRICS, SCO, EAEU, BRICS Bridge); Eurasia (CSTO, nuclear doctrine); energy (shadow fleet); connectivity (Northern Sea Route, Russia-North Korea Treaty). Strategic entente = informal, not alliance.',
    '**US-China:** Thucydides Trap; seven dimensions; Washington v Beijing Consensus; Sept 2026 summit (AI dialogue, $30 bn tariff cuts). Core ideas: tech is a national-security issue; not a new Cold War.',
    '**Russia-West:** Finland 2023, Sweden 2024; Ankara €70 bn; EU gas 45% to 12%; No Limits trade $228 bn. Core idea: not two fixed blocs.',
    '**India frame:** autonomy, multi-alignment, issue-based; US tech, defence, Indo-Pacific; China deterrence and engagement; Russia defence, energy, Eurasia. Jaishankar: engage America, manage China, cultivate Europe, reassure Russia, bring Japan into play.',
    '**India-China phases:** 1950-54 Panchsheel; 1950s-62 rupture; 1976-88 Rajiv visit; 1993-2005 border management; 2008-13 economy; 2017-20 Doklam, Galwan; 2020-24 Depsang-Demchok Oct 2024; 2025-26 re-engagement.',
    '**Border:** 3,488 km = 1,597 western + 545 middle + 1,346 eastern. Aksai Chin (west); McMahon Line (east); Doklam tri-junction. Trade $151 bn; deficit about $112.16 bn.',
    '**China issue boxes:** Pak nexus (CPEC, two-front, Gwadar); String of Pearls (Gwadar, Hambantota, Kyaukpyu); Brahmaputra (upstream); rare earths (90.4% of magnets; Rs 7,280 crore; 6,000 tonnes). Three Mutuals.',
    '**India-US:** partnership not alliance; 1962, 1971 mistrust, Pokhran-II to Talbott, Nuclear deal 2005-08, LEMOA/COMCASA/BECA, iCET to TRUST, Mission 500 ($500 bn by 2030). Frictions: Russia, tariffs 25+25 to 18%, GSP 2019, H-1B 71%, Pakistan, CBDR. Seeks v avoids table.',
    '**India-Russia:** 1947, MiG-21, 1971 Treaty, Aryabhata 1975, Kudankulam 1988, 2000 SP, 2010 SPSP; crude 36.5%; trade $68.7 bn, target $100 bn by 2030; INSTC, Chennai-Vladivostok; S-400, AK-203; triangle with China; trade deficit ($4.3 bn out, $61.4 bn in).',
    '**EU:** 1994, 2004, 2007 FTA talks, 2013 stall, TTC 2022, FTA concluded 2026 (99.5% of exports; dairy excluded); CBAM, GDPR. **France:** Horizon 2047, Rafale 36 + 26 M, Kalvari, Jaitapur, UPI, ISA 2015.',
    '**Japan:** ODA, JPY 10 tn, $40 bn FDI, IJICP, LUPEX, SCRI, CEPA underused. **Australia:** A$50.2 bn, ECTA to CECA, uranium, PACTS, Critical Minerals Corridor, Malabar and AUSINDEX.',
]

TRAPS = [
    ('Balancing, bandwagoning, autonomy', 'Balancing opposes the dominant power; bandwagoning joins it; autonomy decides alone. Rule: Belarus-Russia and Pakistan-China are bandwagoning; India is autonomy.'),
    ('Strategic entente is not an alliance', 'An informal understanding, no formal treaty duty. Rule: Russia-China “No Limits” is an entente, not a military alliance (the handout says so).'),
    ('Power Transition Theory versus Thucydides Trap', 'Theory = conflict is likelier when a rising power nears the dominant one. Trap = the risk when a rising power threatens an established one. Rule: the Trap is the risk label, the Theory is the cause.'),
    ('Not a complete new Cold War', 'Slide 13 and slide 15 both stress interdependence and strategic autonomy. Rule: in an answer, never accept “new Cold War” or “two blocs” without this qualifier.'),
    ('Western, middle and eastern sector lengths', '1,597 (west), 545 (middle), 1,346 (east) = 3,488 km. The middle is the least disputed. Rule: Aksai Chin and Galwan are west; McMahon Line and Doklam are east.'),
    ('Doklam 2017 versus Galwan 2020', 'Doklam: India-Bhutan-China tri-junction (east). Galwan: Ladakh (west). Rule: Doklam = 2017 east; Galwan = 2020 west.'),
    ('Gwadar is not a Chinese naval base', 'The handout warns that commercial access should not automatically be called a naval base. Rule: say “potential maritime dimension”.'),
    ('String of Pearls ports', 'Gwadar, Hambantota, Kyaukpyu in Issue box 2; Chapter 1 also lists Djibouti. Rule: do not mix them with the Diamond Necklace (Chabahar, Duqm, Sabang).'),
    ('Tariff figures', '25% reciprocal + 25% Russian-oil-linked = up to 50%; the 2026 interim deal cut it to 18%. Rule: give the 25+25 split, then 18%.'),
    ('India avoids “forced abandonment of Russia”', 'India seeks closer US defence ties but avoids a forced break with Russia. Rule: use the seeks v avoids table for “partnership without alliance”.'),
    ('Russia’s trade gap', 'India exports about US$4.3 bn and imports about US$61.4 bn (2023-24); trade total US$68.7 bn is FY2024-25. Rule: quote year with each number.'),
    ('Named, not explained', 'AUKUS, Pax Silica, Mythos 5 and Operation Absolute Resolve are named without explanation. (The EU, France, Japan and Australia now have class slides, PPT-4.) Rule: do not invent details; check class notes.'),
]

MCQ = [
    ('Bandwagoning is best described as:', ['opposing a dominant power', 'aligning with a stronger power for security or economic benefits', 'taking independent decisions', 'forming a formal alliance with equals'], 1, 'Slide 2: balancing = opposing; bandwagoning = aligning with a stronger power; strategic autonomy = independent decisions.'),
    ('Which pair is given in the handout as an example of bandwagoning?', ['India-US and Japan-US', 'Belarus-Russia and Pakistan-China', 'Germany-France and Italy-Spain', 'Iran-Saudi Arabia'], 1, 'Belarus-Russia (security, energy, economic support) and Pakistan-China (CPEC, defence, diplomatic backing).'),
    ('The Thucydides Trap refers to:', ['a trade dispute between rivals', 'the risk of conflict when a rising power threatens an established power', 'a financial crisis in a dominant economy', 'an arms control treaty'], 1, 'The handout defines it that way. Power Transition Theory is the related idea about capabilities.'),
    ('Washington Consensus versus Beijing Consensus contrasts:', ['military alliances', 'Western market-led liberal reforms versus a state-led, development-oriented model', 'two trade blocs of equal size', 'two space programmes'], 1, 'Economic rivalry: market-led liberal reforms against state-led development.'),
    ('Which is correct about China’s strategic instruments?', ['BRI, CPEC and Gwadar are part of regional centrality; Djibouti is an overseas facility', 'Djibouti is part of CPEC', 'CPEC is a Russian initiative', 'Gwadar is in Sri Lanka'], 0, 'BRI, CPEC and Gwadar fall under regional economic connectivity; Djibouti is the overseas facility.'),
    ('Russia’s “BRICS Bridge” is proposed as:', ['a military alliance', 'an alternative financial mechanism', 'a trade route', 'a space partnership'], 1, 'The handout and slide 10: an alternative financial mechanism.'),
    ('The “core idea” on slide 13 about US-China rivalry is that:', ['it is a complete new Cold War', 'it is not a complete new Cold War because economic interdependence continues', 'it has ended with the 2026 summit', 'only military power matters'], 1, 'Slide 13: not a complete new Cold War, because economic interdependence continues.'),
    ('Which statement about the India-China border is correct?', ['It is 3,488 km long and runs along five Indian States and UTs listed in the handout', 'The middle sector is the most disputed', 'The western sector is 545 km', 'Doklam is in Ladakh'], 0, '3,488 km: Ladakh, Himachal Pradesh, Uttarakhand, Sikkim, Arunachal Pradesh. Middle sector (545 km) is the least disputed; Doklam is the tri-junction in the east.'),
    ('The October 2024 India-China understanding was about patrolling in:', ['Galwan and Pangong', 'Depsang and Demchok', 'Doklam and Tawang', 'Siachen and Kargil'], 1, 'The 2024 Depsang-Demchok understanding brought cautious tactical stabilisation.'),
    ('In FY 2024-25, the share of India’s metal permanent-magnet imports supplied by China (by quantity) was about:', ['50%', '65.2%', '90.4%', '99.9%'], 2, 'Issue box 4: 90.4% by quantity; India imports all the sintered NdFeB magnets it uses.'),
    ('Which of these is NOT on the “India seeks” side of the India-US table?', ['Defence interoperability', 'Treaty alliance', 'Quad and minilateral cooperation', 'Technology access'], 1, '“Treaty alliance” is on the “India avoids” side.'),
    ('The India-US Civil Nuclear Agreement is placed in which phase?', ['1971 strategic mistrust', '2005-08 nuclear breakthrough', '2016-20 interoperability', '1962 temporary convergence'], 1, 'It ended India’s nuclear isolation and was a turning point in bilateral trust.'),
    ('Which of the following is an India-US friction named in the handout?', ['A 25% reciprocal tariff plus a separate 25% tariff linked to Russian oil', 'A shared nuclear umbrella', 'A treaty alliance clause', 'A common currency'], 0, 'The 2026 interim deal reduced the rate to 18%.'),
    ('The first India-Russia 2+2 Dialogue was held in:', ['2000', '2010', '2021', '2025'], 2, '2021: Institutional coordination row.'),
    ('The Chennai-Vladivostok corridor links India with:', ['Iran and the Caspian', 'the Russian Far East', 'Central Asia', 'Southeast Asia'], 1, 'It supports access to energy, minerals, coal and Arctic trade. INSTC links Iran, the Caspian, Russia and Europe.'),
    ('The India-EU FTA concluded in 2026 covers about what share of India’s exports?', ['50%', '75%', '99.5%', '100%'], 2, 'It covers 99.5% of India’s exports; dairy, cereals and poultry are excluded.'),
    ('Which sequence of India-Japan statements is correct?', ['LUPEX is a lunar polar mission; IJICP is an industrial competitiveness partnership', 'LUPEX is a trade pact; IJICP is a space mission', 'SCRI is a bank; UNICORN is a treaty', 'JIMEX is a trade fair'], 0, 'LUPEX = Joint Lunar Polar Exploration Mission; IJICP = India-Japan Industrial Competitiveness Partnership.'),
]

CARDS = [
    ('Define a major power.', 'A state with significant economic, technological and military capabilities and the strategic intent to shape the international order.'),
    ('Balancing, bandwagoning, strategic autonomy?', 'Balancing: oppose a dominant power. Bandwagoning: align with a stronger power. Strategic autonomy: independent decisions.'),
    ('What is a strategic entente?', 'An informal cooperative understanding to consult or align policies, without necessarily being a formal alliance.'),
    ('US four ambitions?', 'Great-power competition and regional balance; economic, technological and defence superiority; global financial and institutional influence; regional security and Western Hemisphere focus.'),
    ('Island chain in the 2026 US National Defense Strategy?', 'Japan → Taiwan → Philippines → Borneo.'),
    ('Which US laws and frameworks does the handout name?', 'Graham Sanctioning Russia and Iran Act 2026 (up to 100%); CHIPS and Science Act 2022; 2023 AI Framework (CAISI); IPEF.'),
    ('China four ambitions?', 'National rejuvenation; regional centrality and military reach; technological and economic leadership; multipolarity as a path to middle-kingdom status.'),
    ('What is the “New Three”?', 'EVs, lithium-ion batteries and solar PV.'),
    ('China’s global initiatives?', 'Global Development Initiative (GDI), Global Security Initiative (GSI), Global Civilization Initiative (GCI).'),
    ('Russia four ambitions?', 'Multipolarity and strategic autonomy; Eurasian neighbourhood and great-power status; energy and resources as leverage; Eurasian connectivity and partnerships.'),
    ('What is the shadow tanker fleet?', 'Russia’s means of bypassing the G7 oil price cap and EU embargo.'),
    ('Power Transition Theory and Thucydides Trap?', 'Conflict is likelier when a rising power approaches a dominant power; the Trap is the risk of conflict when a rising power threatens an established one.'),
    ('Washington v Beijing Consensus?', 'Western market-led liberal reforms versus China’s state-led, development-oriented model.'),
    ('September 2026 Trump-Xi summit outcome?', 'Proposed US-China AI dialogue; trade truce extended; reciprocal tariff cuts on $30 bn of non-sensitive goods each way.'),
    ('Core idea on US-China?', 'Not a complete new Cold War; economic interdependence continues. Technology is a national-security issue.'),
    ('When did Finland and Sweden join NATO?', 'Finland 2023, Sweden 2024.'),
    ('EU dependence on Russian gas?', 'Fell from 45% (2021) to 12% (2025); January 2026 Regulation to phase out Russian pipeline gas and LNG.'),
    ('Russia-China “No Limits” trade?', 'About $228 billion (2025); based on shared interests, not a formal military alliance.'),
    ('India’s approach to major-power competition?', 'Strategic autonomy, multi-alignment, issue-based partnerships; partner widely, align selectively, depend permanently on none.'),
    ('Jaishankar’s line?', 'Engage America, manage China, cultivate Europe, reassure Russia, bring Japan into play, draw neighbours in, extend the neighbourhood, expand traditional constituencies of support.'),
    ('India-China nature (slide 17)?', 'Competition + interdependence + selective cooperation: managed competition.'),
    ('India-China phase keywords?', 'Postcolonial engagement, territorial rupture, diplomatic rapprochement, institutionalised border management, economic engagement, border confrontation, crisis management, calibrated re-engagement.'),
    ('Border sectors and lengths?', 'West (Ladakh) 1,597 km; middle (Himachal, Uttarakhand) 545 km, least disputed; east (Sikkim, Arunachal) 1,346 km. Total 3,488 km.'),
    ('Four China issue boxes?', 'China-Pakistan nexus; String of Pearls; Brahmaputra; rare-earth magnets.'),
    ('Rare-earth magnet numbers?', 'China supplied 90.4% by quantity (FY 2024-25); demand 8,220 tonnes a year by 2030; Rs 7,280-crore scheme for 6,000 tonnes capacity.'),
    ('Three Mutuals?', 'Mutual respect, mutual sensitivity, mutual interests.'),
    ('India-US nature?', 'Partnership, not alliance: strategic convergence with continuing policy differences.'),
    ('India-US defence enablers?', 'LEMOA (2016, logistics), COMCASA (secure communications), BECA (2020, geospatial); 2025 ten-year defence framework.'),
    ('iCET and Mission 500?', 'iCET → TRUST for strategic technology; Mission 500 targets US$500 bn goods trade by 2030.'),
    ('Tariff story?', '25% reciprocal + 25% Russian-oil-linked; a 2026 interim deal cut it to 18%.'),
    ('India seeks versus India avoids (US)?', 'Seeks interoperability, technology access, exercises, maritime cooperation, Quad, minerals, defence ties, trade expansion. Avoids treaty alliance, tech dependence, automatic war commitments, foreign bases, anti-China bloc, single-source dependence, forced abandonment of Russia, damaging market opening.'),
    ('India-Russia milestones?', '1947 relations; 1960s MiG-21; 1971 Treaty; 1975 Aryabhata; 1988 Kudankulam; 2000 SP; 2010 SPSP; 2021 2+2.'),
    ('India-Russia numbers?', 'Crude about 1.92 mbd (36.5%) in May 2026; trade US$68.7 bn (FY2024-25), target US$100 bn by 2030; exports US$4.3 bn v imports US$61.4 bn (2023-24).'),
    ('Russia-China-India triangle responses?', 'Diversify Russia’s links with India; use Chabahar, INSTC and SCO; use BRICS/SCO for reform; protect LNG, coking coal and rare-earth interests.'),
    ('India-EU FTA features?', 'Concluded 2026; covers 99.5% of exports; duty-free for textiles and leather; dairy, cereals, poultry excluded; mobility for IT professionals, nurses, consultants.'),
    ('India-France highlights?', 'Horizon 2047 (2023); Special Global Strategic Partnership (Feb 2026); 36 Rafale + 26 Rafale-M; six Kalvari submarines; Jaitapur; UPI; ISA 2015.'),
    ('India-Japan highlights and gaps?', 'ODA to strategy; JPY 10 tn target; LUPEX; SCRI. Gaps: execution, CEPA underuse, defence tech transfer.'),
    ('India-Australia highlights?', 'A$50.2 bn trade; ECTA to CECA; uranium exports; PACTS; Critical Minerals Corridor; Malabar, AUSINDEX, AUSTRAHIND.'),
]

# (title, intro, body list, closing)
SKELETONS = [
    ('Mains 2026 (15m, 250w): BRI and South Asia as a theatre of great-power competition',
     'Intro: the BRI (2013) uses ports, railways and corridors (CPEC, Gwadar) to deepen China’s regional centrality, and South Asia has become a space where China, India and the US compete.',
     ['Security: CPEC through PoK is a sovereignty objection; China-Pakistan defence cooperation complicates two-front planning; Gwadar adds a potential maritime dimension (do not call it a naval base).',
      'Indian Ocean: String of Pearls (Gwadar, Hambantota, Kyaukpyu), research vessels, naval reach; India’s response: maritime domain awareness, neighbourhood partnerships, SAGAR/MAHASAGAR, Quad.',
      'Regional influence: Chinese infrastructure money competes with Indian connectivity; India must offer faster, reliable projects (way forward).',
      'Critical view: “theatre of competition” is partly true, but South Asia states also hedge; India is more than a reactor (Quad, Act East, partnerships).'],
     'Closing: BRI raises the stakes for India’s security and influence; the answer is delivery, partnerships and deterrence, not rejection alone.'),
    ('Mains 2024 (10m, 150w): the West fostering India as an alternative to China',
     'Intro: US-China rivalry and Russia-West confrontation have pushed the West to look for trusted partners and diversified supply chains.',
     ['Supply chains: China+1 and friend-shoring open opportunities for India in electronics, semiconductors, pharmaceuticals; the EU lists semiconductors, pharma, medical devices, critical minerals; Australia, France, Japan on minerals and manufacturing.',
      'Strategic ally: Quad and Malabar, India-US defence framework and iCET/TRUST, India-France co-production, Japan’s JPY 10 tn target.',
      'Limits: dependence on Chinese inputs (rare-earth magnets 90.4%), Russia ties and strategic autonomy, trade frictions (tariffs, CBAM), execution gaps (Japan).'],
     'Closing: the West sees India as a partner, not a proxy; India accepts it on its own terms.'),
    ('Mains 2023 (15m, 250w): NATO expansion and a stronger US-Europe partnership: good for India?',
     'Intro: the Ukraine war expanded NATO (Finland 2023, Sweden 2024) and tightened US-Europe coordination. For India the effect is mixed.',
     ['Gains: West looks to India for supply chains and technology; EU FTA, TTC; France and US defence co-production; India gets scope for diversification away from Russia.',
      'Costs: sanctions on Russia hit India’s defence spares and energy; Graham Act 2026; India-Russia-China triangle can reduce India’s space in Eurasia; pressure on strategic autonomy.',
      'India’s response: dialogue and diplomacy on Ukraine, no automatic alignment, multi-alignment, defence diversification and indigenisation.'],
     'Closing: only partly: it widens India’s options but also raises costs on Russia ties; autonomy decides the net effect.'),
    ('Mains 2021 (15m, 250w): AUKUS and existing partnerships (thin notes: AUKUS is only named)',
     'Intro: AUKUS is listed among US minilateral groupings that strengthen regional deterrence. (The notes give no more detail: add AUKUS facts after class before using this in the exam.)',
     ['Context from the notes: the US builds flexible coalitions (NATO, Quad, I2U2, AUKUS) to prevent China’s regional dominance; alliances with Japan, South Korea, Australia and the Philippines.',
      'Existing partnerships: Quad and Malabar for maritime security and technology; India-Australia cooperation (Malabar, AUSINDEX, PACTS); minilateralism supplements, not replaces, existing groupings (Chapter 1).',
      'Verdict frame: AUKUS adds a layer; it does not supersede the Quad or ASEAN-centred mechanisms.'],
     'Closing: another coalition layer in a multipolar churn, not a replacement.'),
    ('Mains 2020 (15m, 250w): Indo-US over Indo-Russian defence deals and the Indo-Pacific',
     'Intro: defence ties with the US are moving from arms purchases to interoperability, co-production and technology; Russia remains a legacy and maintenance pillar.',
     ['US: LEMOA 2016, COMCASA, BECA 2020, 2+2, 2025 ten-year framework, defence trade about $25 bn by end-2023; Quad and Malabar for Indo-Pacific stability.',
      'Russia: Su-30MKI, T-90, S-400, AK-203, INS Vikramaditya; MRO; shift to licensed production; but S-400 delays, spares, payment and sanctions risks.',
      'Indo-Pacific stability: US partnership supports freedom of navigation and a balance against China; Russian systems are continental in focus (the handout).',
      'India’s approach: diversify suppliers; CAATSA objection; no forced abandonment of Russia.'],
     'Closing: significance of US deals lies in interoperability and technology; Russia stays a legacy pillar; India diversifies.'),
    ('Mains 2020 (15m, 250w): Quad, from military alliance to trade bloc?',
     'Intro: the Quad is a minilateral grouping for a free, open and rules-based Indo-Pacific, not a treaty alliance.',
     ['Test the claim: the notes link the Quad with Malabar, maritime security, resilient supply chains and critical technologies. No trade bloc features are named.',
      'India avoids “a formal anti-China military bloc”, “treaty alliance” and “automatic war commitments” (India seeks v avoids).',
      'Wider footing: IPEF and friend-shoring (US), SCRI (India, Japan, Australia), PACTS and the Critical Minerals Corridor (Australia).'],
     'Closing: the Quad is a multi-issue minilateral: security plus supply chains and technology; “trade bloc” overstates the shift.'),
    ('Mains 2019 (15m, 250w): why friction between India and the US',
     'Intro: ties moved from Cold War mistrust (1971) to strategic partnership, but a “partnership, not alliance” leaves gaps in expectations.',
     ['The statement’s core: the US expects closer alignment; India wants issue-based cooperation, autonomy and recognition of its ambitions.',
      'Examples: Russia (S-400, CAATSA, oil); tariffs and GSP removal (2019); Pakistan (re-hyphenation, mediation); H-1B and student safety; defence technology limits; values and sovereignty.',
      'Counter-evidence: Nuclear Agreement 2005-08, LEMOA/BECA, iCET, Quad.'],
     'Closing: friction comes from different expectations of India’s role, but converging interests keep the partnership growing.'),
    ('Mains 2019 (10m, 150w): India and Japan, a global and strategic partnership',
     'Intro: India-Japan has moved from ODA-led cooperation to a strategic and economic partnership around a free, open Indo-Pacific.',
     ['Strategic: Quad, JAI, Malabar; JIMEX; 2+2, ACSA; SCRI; LUPEX and AI dialogue.',
      'Economic: JPY 10 tn target; Delhi Metro, Western DFC, high-speed rail; Act East Forum; Asia-Africa Growth Corridor.',
      'Gaps: trade below potential; execution delays; CEPA underuse; limited defence-technology transfer.'],
     'Closing: significance for Asia and the world is real; the test is turning convergence into projects.'),
    ('Mains 2018 (15m, 250w): US-Iran nuclear pact and India (thin notes)',
     'Intro: the notes do not cover the US-Iran nuclear pact; they cover the Iran-linked pieces below. Add the pact’s details after class.',
     ['Connectivity: INSTC complements Chabahar; Iran and Central Asia routes matter more if Russia-West tension affects INSTC.',
      'Sanctions: the Graham Act 2026 extends Iran sanctions (a risk for India’s energy and connectivity choices).',
      'India’s response in the notes’ frame: strategic autonomy and issue-based partnerships; diversify energy; avoid taking sides.'],
     'Closing: India’s interests (energy, Chabahar, INSTC) argue for autonomy and quiet diplomacy.'),
    ('Mains 2017 (10m, 150w): China’s trade surplus and military ambitions',
     'Intro: China’s manufacturing scale and export position fund its military modernisation and regional reach.',
     ['Economic: trade deficit about $112.16 bn (FY2025-26); dependence on rare earths, graphite, electronics; telecom and cyber risks.',
      'Military reach: PLA, A2/AD, Two-Ocean strategy, Djibouti; BRI, CPEC, Gwadar, String of Pearls.',
      'India’s response: de-risking, domestic capacity (Rs 7,280-crore magnet scheme), Maritime Domain Awareness, Quad, LAC preparedness, selective engagement.'],
     'Closing: economic interdependence is also a vulnerability; India combines engagement with de-risking.'),
]
