# -*- coding: utf-8 -*-
# Chapter 3: Bhutan, Myanmar, Sri Lanka, Maldives, comparison; map, timeline, links, recall, traps, quiz, cards, skeletons
from lib import *

PRIORITY = 'High'


def build_rest(secs):
    # ---------------------------------------------------------------- 10 Bhutan
    secs.append(Sec('India-Bhutan', [
        p('Among India’s **most stable partnerships**, built on strategic trust, security convergence and development cooperation. Governed by the **2007 Treaty of Friendship**, ties are evolving through hydropower, connectivity and **Gelephu Mindfulness City**, amid Bhutan-China boundary talks and **Doklam/Siliguri Corridor** sensitivities. The “**Bharat for Bhutan, Bhutan for Bharat” (B4B)** framework reflects mutual trust and strategic interdependence.'),
        tbl('Nature of the relationship (slide 26, handout p. 16)', ['Nature', 'Meaning'], [
            ['Strategic trust', 'The 2007 Treaty and regular consultations'],
            ['Development partnership', 'Bhutan sees India as its **principal development and security partner**'],
            ['Security convergence', 'A stable, sovereign Bhutan matters for Himalayan and regional security'],
            ['Hydropower anchor', 'Energy cooperation remains central'],
            ['New areas', 'Gelephu Mindfulness City, digital, space and renewables'],
        ]),
        teacher('Class slide stress: “Core idea” (slide 26)', '**Bharat for Bhutan, Bhutan for Bharat.**'),
        tbl('Evolution (slide 27, handout p. 16)', ['Phase', 'Keyword', 'Key developments'], [
            ['Pre-1949 to 1978', 'Civilisational ties and formalisation', 'Buddhist links; the **1949 Friendship Treaty** created the formal framework; diplomatic relations deepened gradually'],
            ['2003-07', 'Security to sovereign partnership', '**Operation All Clear (2003)** strengthened security cooperation. The **2007 Treaty** modernised the relationship and recognised Bhutan’s **greater foreign-policy autonomy**'],
            ['2014-17', 'Strategic partnership', 'Neighbourhood First; the **Doklam standoff (2017)** showed Bhutan’s importance for Himalayan and **Siliguri Corridor** security'],
            ['2019-present', 'Diversification and deepening', 'Beyond hydropower into digital, space, connectivity, infrastructure and economic diversification; security cooperation continues'],
        ]),
        tbl('Areas of convergence (slide 28, handout pp. 16-17)', ['Area', 'Key points'], [
            ['Trade and investment', 'India is Bhutan’s **largest trading partner**: **₹12,669 crore (2024)**. India accounts for **over 55% of Bhutan’s FDI**. The **2016 Trade, Commerce and Transit Agreement**: free bilateral trade and duty-free transit for Bhutan’s third-country trade'],
            ['Development assistance', '**₹10,000 crore** for Bhutan’s **13th Five-Year Plan (2024-29)**, including **572 High-Impact Community Development Projects**'],
            ['Connectivity', 'A **September 2025 MoU** for the proposed **Kokrajhar-Gelephu and Banarhat-Samtse rail links**. The **Darranga immigration post** and **Samrang land customs station** are operational. India supports **Gelephu Mindfulness City**; road and rail links can improve its access to Assam'],
            ['Hydropower and energy', '**Five major hydropower projects, 3,156 MW**, jointly developed. The **1,020 MW Punatsangchhu-II** completed final unit commissioning in **2025**. **Two-way power trade**: Bhutan exports surplus and imports Indian power in winter. A **₹4,000-crore concessional line of credit** for energy projects (July 2026). The **2024 Joint Vision Statement** and **2025 MoU on Renewable Energy** extend ties to solar and green hydrogen'],
            ['Defence and security', 'The **Indian Military Training Team (IMTRAT)** trains Bhutanese forces. Regular Secretary-level meetings on border management. The 2007 Treaty frames consultation on Himalayan security'],
            ['Digital, space, health', '**RuPay** works in both countries; Indian **UPI apps pay through Bhutan’s national QR system**. The **India-Bhutan satellite** (launched **2022**; ground station in Bhutan **2023**). India’s **National Knowledge Network** connects with **DrukREN**. **AIIMS-Khesar Gyalpo University MoU (July 2026)**. Indian support helped build Thimphu’s **Jigme Dorji Wangchuck National Referral Hospital**. Bhutan was the **first country** to receive COVID-19 vaccines under **Vaccine Maitri**'],
            ['Culture and people', 'The **Royal Bhutan Temple at Rajgir** (completed 2025); land for a Bhutanese temple in **Varanasi**. About **1,900 Bhutanese students** on Indian scholarships (2025-26); about **325 ITEC seats** a year. The **India-Bhutan Foundation**. About **50,000 Indians** work in Bhutan'],
            ['Multilateral', 'Both are founding members of **SAARC**; **BBIN and BIMSTEC**; the **International Solar Alliance**'],
        ]),
        fig('img/ir-nb-gelephu.jpg', 'Gelephu Mindfulness City in southern Bhutan, close to Assam (handout p. 16).', 'Handout map'),
        tbl('Areas of divergence (slide 28, handout p. 17)', ['Area', 'Key points'], [
            ['Boundary talks', 'Bhutan and China continue negotiations on their disputed boundary. Any settlement near **Doklam** affects India’s adjoining security interests'],
            ['BBIN', 'Bhutan signed the **2015 BBIN Motor Vehicles Agreement** but has **not ratified** it, citing traffic and environmental effects'],
            ['Hydropower and finance', '**Punatsangchhu-I (1,200 MW)**: geological instability delayed it far beyond its **2015** target. Electricity is **12-15% of Bhutan’s GDP**, so delays hit revenue. India financed **Punatsangchhu-I with a 60% loan** and **Punatsangchhu-II with a 70% loan**, raising Bhutan’s debt share'],
            ['Economic imbalance', 'India is about **80% of Bhutan’s trade (2026)**. India exported **₹9,538 crore** and imported **₹3,131 crore (2024)**'],
            ['Connectivity', 'The rail links are **planned, not operating**'],
            ['Political', '**2013**: India’s withdrawal of **LPG and kerosene subsidies** during Bhutan’s election campaign fuelled perceptions of political pressure'],
        ]),
        tbl('Way forward (slide 29, handout p. 18)', ['Area', 'Way forward'], [
            ['Economic diversification', 'Tourism, fintech, digital services, biotechnology, food processing; blended finance and Indian investment that build Bhutanese skills and jobs; link Gelephu with Indian infrastructure, skills and investment'],
            ['Connectivity and energy', 'Fast-track the two rail links with clear financing, timelines and environmental safeguards; **BBIN grid rules**; climate-proof hydropower against glacial floods and changing river flows'],
            ['People and culture', 'Buddhist tourism, education and skills; easier cross-border movement with safeguards'],
            ['Security', '**Sovereignty-first consultation on Doklam**, respecting Bhutan’s independent boundary negotiations with China; real-time information sharing against terrorism, drugs and transnational crime'],
            ['Strategic trust', 'Deepen connectivity and investment while respecting Bhutan’s development priorities and its **sovereign engagement with China**'],
        ]),
        callout('key', 'Conclusion', 'The partnership rests on political trust, development and security cooperation, but must **move beyond hydropower dependence**. Bhutan-China talks, Doklam and Gelephu call for sovereign respect, economic diversification and faster delivery.'),
    ], label='Class + handout'))

    # ---------------------------------------------------------------- 11 Myanmar
    secs.append(Sec('India-Myanmar', [
        p('One of India’s **most complex neighbourhood relationships**: border security, Act East connectivity, China’s influence, refugee flows and democratic concerns. Since the **2021 coup**, Myanmar has faced civil war, ethnic conflict and a deepening humanitarian crisis. For India the question is **not whether to engage, but with whom, on what issues and to what extent**.'),
        tbl('Nature of the relationship (slide 30, handout p. 19)', ['Nature', 'Meaning'], [
            ['Necessary but difficult partner', 'Internal instability directly affects India’s border regions and eastern outreach; India cannot disengage'],
            ['Calibrated engagement', 'Deal carefully with different political and ethnic actors'],
            ['Security priority', 'Insurgency, trafficking, border management'],
            ['Connectivity priority', 'Kaladan and the Trilateral Highway'],
            ['Values-security balance', 'Concern for democracy, stability and humanitarian conditions alongside strategic interests'],
        ]),
        tbl('Evolution (slide 31, handout p. 19)', ['Phase', 'Keyword', 'Key developments'], [
            ['Ancient-1951', 'Civilisational and diplomatic foundation', 'Buddhism, trade and colonial links (slide: **Burma linked to British India till 1937**). The **1951 Treaty of Friendship**'],
            ['1960s-1988', 'Political distance', 'Military rule, economic isolation and nationalisation strained ties. **Rajiv Gandhi’s 1987 visit** improved engagement; the **1988 crackdown** and India’s support for democracy set it back'],
            ['1990s-2000s', 'Look East and strategic re-engagement', 'Re-engagement for Northeast security, connectivity and China-related concerns. **Kaladan**, border trade and defence cooperation'],
            ['2014-20', 'Act East partnership', 'Myanmar became a key pillar of Act East'],
            ['2021', 'Coup and strategic dilemma', 'India had to balance democratic concerns with security and connectivity interests'],
            ['2024-25', 'Conflict and humanitarian pressure', 'Refugee flows and border-security pressures; **Operation Brahma (2025)** reinforced India’s humanitarian role'],
            ['2025-26', 'Pragmatic engagement', 'Engagement on border security, connectivity and strategic interests amid contested political legitimacy'],
        ]),
        tbl('Areas of convergence (slide 32, handout pp. 19-20)', ['Area', 'Key points'], [
            ['Trade', 'Bilateral trade **US$2.15 billion (2024-25)**, up from about **US$1.74 billion (2023-24)**. Myanmar supplies **pulses and beans**; India exports **pharmaceuticals**. The **Rupee-Kyat settlement mechanism** began in **May 2024**; both agreed in 2026 to expand it'],
            ['Connectivity', 'The **Kaladan Multi-Modal Transit Transport Project** links **Kolkata-Sittwe-Mizoram**: an alternative route to the Northeast. The **India-Myanmar-Thailand Trilateral Highway**. Myanmar is in **ASEAN and BIMSTEC**; **Mekong-Ganga Cooperation**'],
            ['Security', 'Vital for Northeast access and for keeping each side’s territory from being used against the other; regular political and security dialogue'],
            ['Development', 'Support for socio-economic development, peace and national reconciliation. **ICCR scholarships**; Mekong-Ganga scholarship slots raised **from 36 to 100 in 2026**. Training of officials in IT, banking, audit and accounts'],
            ['Humanitarian', '**Operation Brahma** after the **March 2025 earthquake**: relief by air and sea. Shared ethnic and family ties along the border'],
            ['Culture', 'Buddhist traditions and pilgrimage. India supported restoration of the **Ananda Temple, Bagan**. An estimated **2 million** people of Indian origin'],
        ]),
        tbl('Areas of divergence (slide 32, handout p. 20)', ['Area', 'Key points'], [
            ['Border and crime', 'The **1,643 km** border runs through mountains and forest. Insurgency, arms smuggling, drug and human trafficking, cybercrime and illicit finance through the **Death Triangle**. India’s **fencing plans and tighter Free Movement Regime (FMR) rules** face opposition in **Mizoram** and among **Naga** communities'],
            ['Conflict and refugees', 'Post-2021 conflict has pushed displaced people into the Northeast. Fighting near the border raises risks of insurgent movement and arms flows. Instability in **Rakhine** complicates the Rohingya problem'],
            ['China', 'Infrastructure, connectivity and conflict mediation, including the **Kyaukphyu deep-water port**. It affects India’s Bay of Bengal access, connectivity projects and Act East'],
            ['Connectivity gaps', '**Sittwe port** received its **first Indian cargo in 2023**, but the full Kaladan corridor to Mizoram is **unfinished**. Security and delays affect the Trilateral Highway'],
            ['Political dilemma', 'India supports peace, an end to violence, dialogue and democratic transition. Myanmar’s **military-led political process** complicates this, yet India must engage the authorities on border, connectivity and strategic interests: **values versus national interests**'],
        ]),
        tbl('Way forward (slide 33, handout pp. 20-21)', ['Area', 'Way forward'], [
            ['Diplomacy', 'Regular dialogue, respecting sovereignty and domestic processes. Clearly define the role, ownership and operating arrangements of Indian-supported projects'],
            ['Border and maritime', 'Information sharing, surveillance, joint patrolling, search-and-rescue. Manage the **FMR** so legitimate community and economic links are protected while misuse is checked'],
            ['Connectivity', 'Complete and use **Kaladan** and the **Trilateral Highway**; secure, climate-resilient, commercially viable links'],
            ['Development', 'Assistance, concessional finance, capacity-building; scholarships, healthcare, community programmes'],
            ['Refugees', 'Work with stakeholders on refugee flows; support **safe, voluntary and sustainable return** when circumstances permit'],
            ['Regional', 'Use **BIMSTEC, Mekong-Ganga Cooperation**; advance Act East, Neighbourhood First and **MAHASAGAR** through Myanmar; offer credible partnerships while **avoiding zero-sum competition with China**'],
        ]),
        teacher('Class slide stress: “Conclusion” (slide 33)', '**Myanmar tests India’s ability to balance values, security and connectivity. The best approach is calibrated engagement.** The handout adds: border regulation, humanitarian sensitivity and faster connectivity delivery.'),
    ], label='Class + handout'))

    # ---------------------------------------------------------------- 12 Sri Lanka
    secs.append(Sec('India-Sri Lanka', [
        p('Relations are shaped by **civilisational ties, maritime proximity, Tamil sensitivities, fisheries disputes and China’s Indian Ocean presence**. Ties are shifting **from crisis assistance to structured connectivity**: energy, ports, UPI, ferries and maritime security. Sri Lanka’s location supports India’s **MAHASAGAR** and Neighbourhood First.'),
        tbl('Nature of the relationship (slide 34, handout p. 22)', ['Nature', 'Meaning'], [
            ['Civilisational link', 'Buddhism, Ramayana memory and Indian Ocean culture'],
            ['Maritime proximity', 'Palk Strait and Indian Ocean security'],
            ['Political sensitivity', 'The Tamil issue; domestic politics in both countries can influence relations'],
            ['Connectivity agenda', 'Energy, ports, UPI, ferries and maritime security'],
            ['MAHASAGAR relevance', 'Sri Lanka is key to India’s Indian Ocean policy'],
        ]),
        tbl('Evolution (slide 35, handout p. 22)', ['Phase', 'Keyword', 'Key developments'], [
            ['Ancient-1970s', 'Civilisational and diplomatic foundation', 'Buddhist, cultural and maritime links. The **Sirimavo-Shastri Pact** addressed Indian-origin Tamils'],
            ['1983-2009', 'Tamil conflict to post-war phase', 'The **Indo-Sri Lanka Accord**, the **IPKF** experience and civil war strained ties. After 2009 India backed Sri Lanka’s territorial integrity and stressed Tamil reconciliation'],
            ['2010s', 'Development and maritime cooperation', 'Housing, reconstruction, energy and maritime cooperation; China’s **Hambantota** presence added a strategic dimension'],
            ['2020-22', 'Crisis partnership', '**Vaccine Maitri** and about **US$4 billion** during the **2022 economic crisis**: first responder and stabilising partner'],
            ['2024-25', 'Connectivity and energy', 'Under **President Dissanayake**: grid connectivity, LNG, pipelines, UPI, ferries, renewables'],
            ['2025-26', 'Maritime and disaster cooperation', '**Operation Sagar Bandhu** and continued maritime-security engagement'],
        ]),
        alert('Handout alert: when was the FTA?', 'The handout speaks of “the **2000 ISFTA**”. Slide 35 lists “**1998**: Economic partnership, India-Sri Lanka FTA”. The material does not explain the two years. Rule for the exam hall: write “India-Sri Lanka Free Trade Agreement (ISFTA)” and, if a year is needed, check your class notes first.'),
        tbl('Areas of convergence (slide 36, handout pp. 22-23)', ['Area', 'Key points'], [
            ['Trade and finance', 'Merchandise trade **US$7.18 billion (FY 2025-26)**. Cumulative Indian investment **US$2.94 billion by 2025**. Talks continue on the **Economic and Technology Cooperation Agreement (ETCA)**. In 2022 India gave about **US$4 billion** in financing and supplies and **co-chaired the Official Creditor Committee** for debt restructuring'],
            ['Development and connectivity', 'A housing project of **60,000 planned houses** in four phases, **10,000 for plantation workers**. The **Maho-Omanthai railway** upgrade (April 2025). A **US$65 million grant** for **Kankesanthurai port**. The **Nagapattinam-Kankesanthurai ferry**; **Chennai-Jaffna flights**. **UPI QR payments** launched in **February 2024**'],
            ['Energy', 'The **Sampur solar project** broke ground; an **HVDC power-interconnection MoU (April 2025)**. India, Sri Lanka and the **UAE** signed an April 2025 MoU to develop **Trincomalee as an energy hub**'],
            ['Humanitarian and people', 'After **Cyclone Ditwah (November 2025)**, **Operation Sagar Bandhu** delivered over **1,058 tonnes** of relief; a **US$450 million recovery package**. More than **2,500 years** of cultural contact; support for **Thirukoneswaram, Sita Eliya and Anuradhapura**. India was the **largest tourist source in 2025 (22.5%)**'],
            ['Defence and security', 'The **April 2025 defence MoU**; **Mitra Shakti** (army) and **SLINEX** (navy). India helped set up Sri Lanka’s **Maritime Rescue Coordination Centre** (commissioned June 2024). The **Colombo Security Conclave**'],
            ['Regional', '**SAARC, BIMSTEC, IORA**; the Official Creditor Committee'],
        ]),
        fig('img/ir-nb-palk.jpg', 'Palk Strait, Palk Bay and the Gulf of Mannar between Tamil Nadu and Sri Lanka, with the maritime boundary as a dashed line (handout p. 23, slide 37).', 'Handout map'),
        tbl('Areas of divergence (slide 36, handout p. 23)', ['Area', 'Key points'], [
            ['Tamil devolution', 'India seeks meaningful implementation of the **13th Amendment** (Provincial Councils). In **April 2025** PM Modi urged **Provincial Council elections**. Inclusion of Tamil and Muslim communities is a wider reconciliation challenge'],
            ['Katchatheevu and fisheries', 'The **1974 maritime agreement** places **Katchatheevu** on Sri Lanka’s side; fishing rights stay contentious in Tamil Nadu. The **1976 agreement** restricted fishing in each other’s waters without permission. India protested after **firing near Delft Island (January 2025)** during the apprehension of Indian fishermen. **Bottom trawling** adds ecological and livelihood concerns'],
            ['Economic and energy', 'In FY 2025-26 India exported about **US$5.5 billion** and imported about **US$1.66 billion**. **Adani Green withdrew** from the **Mannar and Pooneryn** wind projects after Sri Lanka sought to renegotiate. The power interconnection is **not yet operational**'],
            ['Strategic', 'Chinese involvement in **Hambantota**: the perceived **String of Pearls**'],
        ]),
        tbl('Way forward (slide 38, handout p. 24)', ['Area', 'Way forward'], [
            ['Reconciliation', 'Support a **Sri Lankan-led** implementation of the 13th Amendment, equal rights for Tamils and reconciliation'],
            ['Maritime security', 'Expand SLINEX, joint patrols, coast-guard training, maritime domain awareness; **transparent protocols for foreign research-vessel visits**'],
            ['Fisheries', 'A **joint fisheries framework**: talks among fishing communities and governments, designated or seasonal arrangements, a **time-bound shift from bottom trawling**'],
            ['Economy', 'Move **from emergency assistance to transparent, viable investments**; advance **ETCA/CEPA**; expand ferries; turn the 2025 grid MoU into a financed project'],
            ['Digital and people', 'Digital payments, e-governance, healthcare, climate technology; tourism, culture, scholarships, skills'],
        ]),
        callout('key', 'Conclusion', 'Anchor the relationship in **Neighbourhood First and MAHASAGAR**: maritime security with economic recovery, connectivity and people-centric development. A durable partnership needs **strategic trust, sensitivity to Tamil and fisheries concerns, and timely delivery**.'),
    ], label='Class + handout'))

    # ---------------------------------------------------------------- 13 Maldives
    secs.append(Sec('India-Maldives', [
        p('The Maldives sit in the **Central Indian Ocean**, near the sea lanes carrying India’s trade and energy. India’s role as “**First Responder**” (**Operation Cactus**, the **2004 tsunami**, the **2014 Malé water crisis**) supports strong security ties. Relations moved from a sharp “**India Out**” phase to a **cautious reset**, driven by economic support, maritime cooperation and respect for sovereignty.'),
        tbl('Nature of the relationship (slide 39, handout p. 25)', ['Nature', 'Meaning'], [
            ['Maritime neighbour', 'Close to India’s sea lanes and maritime approaches'],
            ['First Responder role', 'Operation Cactus, tsunami relief and Operation Neer'],
            ['Sovereignty sensitivity', 'Domestic politics can create mistrust or demands for distance from India'],
            ['Strategic recalibration', 'From “India Out” to cautious reset'],
            ['China factor', 'A growing Chinese footprint in the Indian Ocean'],
        ]),
        tbl('Evolution (slide 40, handout p. 25)', ['Phase', 'Keyword', 'Key developments'], [
            ['1965-88', 'Diplomatic and security foundation', 'India recognised the Maldives after independence; the **1976 Maritime Boundary Agreement** and **Operation Cactus (1988)** built early strategic trust'],
            ['2004-14', 'First-responder role', 'Help after the **2004 tsunami** and **Operation Neer (2014)**'],
            ['2016-23', 'Defence cooperation to India First', 'The **2016 defence framework** and the **Solih-era “India First”** approach expanded infrastructure, defence and capacity-building'],
            ['2023', 'India Out phase', '**President Muizzu** was elected on an “India Out” platform and demanded withdrawal of Indian military personnel'],
            ['2024', 'Sovereignty-sensitive reset', 'Indian military personnel were **replaced by civilian technical staff**. Muizzu’s India visit produced the **Comprehensive Economic and Maritime Security Partnership**'],
            ['2024-25', 'Economic and connectivity cooperation', 'RuPay, Hanimaadhoo runway, housing, the Greater Malé Connectivity Project and currency support'],
            ['Current phase', 'Strategic recalibration', 'Balancing maritime security, economic engagement and respect for Maldivian sovereignty amid China’s growing presence'],
        ]),
        alert('Handout alert: 1976 or 1979?', 'The handout dates the **Maritime Boundary Agreement to 1976**. Slide 40 lists “**1979**: Maritime cooperation, Maritime Boundary Agreement”. Rule for the exam hall: use the handout’s 1976 and check your class notes.'),
        tbl('Areas of convergence (slide 41, handout pp. 25-26)', ['Area', 'Key points'], [
            ['Maritime security', 'The **Comprehensive Economic and Maritime Security Partnership (October 2024)**. Exercises **Ekuverin and Ekatha** (bilateral) and **Dosti** (with Sri Lanka). The **Colombo Security Conclave** and the **Defence Cooperation Dialogue**. Shared concerns: radicalisation, violent extremism, criminal networks'],
            ['Finance and digital', 'Trade **US$771.76 million (FY 2025-26)**; the **first round of FTA negotiations concluded in July 2026**. The **2024 RBI currency swap**: up to **US$400 million and ₹30 billion**. **RuPay** and the **Favara-UPI integration (operational since July 2026)**'],
            ['Infrastructure', 'The **US$500 million Greater Malé Connectivity Project**. The India-funded new runway at **Hanimaadhoo International Airport** (inaugurated October 2024)'],
            ['People and capacity', 'Shared Buddhist and cultural heritage; Indian-supported restoration of heritage sites. About **60,000 Indians** live in the Maldives. India trained **1,000 Maldivian civil servants (2019-24)**; another 1,000 in 2024-29'],
        ]),
        tbl('Areas of divergence (slide 41, handout p. 26)', ['Area', 'Key points'], [
            ['Sovereignty', 'The **“India Out” campaign (2023-24)** portrayed Indian defence personnel and assets as threats to sovereignty. The Maldives **did not renew the joint hydrographic survey agreement in 2024**'],
            ['China', 'Permission for a **Chinese research vessel to dock in 2024** raised concerns over surveillance and access. India-assisted projects such as the **Uthuru Thila Falhu (UTF) Harbour** have faced suspicion about strategic use'],
            ['Trade imbalance', 'The Maldives imports a large share of essentials from India; its export base to India is narrow. The **China-Maldives FTA entered into force in January 2025**; the India-Maldives FTA is still being negotiated'],
            ['Tourism', 'Slide 41: **tourism was affected by political rhetoric**'],
        ]),
        alert('Handout alert: a garbled line', 'The handout’s fourth divergence point (“Tourism and People-to-People Ties”) is cut off in print. The slide gives the sense: tourism affected by political rhetoric. Check your class notes for the detail.'),
        tbl('Way forward (slide 42, handout pp. 26-27)', ['Area', 'Way forward'], [
            ['Sovereignty-sensitive engagement', 'Respect Maldivian sovereignty and domestic processes. **Clearly define ownership, personnel and operating rules** for Indian-supported aircraft and security assets. Better public communication on Indian assistance'],
            ['Maritime security', 'Information sharing, vessel monitoring, search-and-rescue, disaster response, **keeping operational decisions with Maldivian authorities**. Use **MAHASAGAR** and the **Colombo Security Conclave**'],
            ['Economic integration', 'Grants and concessional finance with transparent costs and debt-sustainability checks; **accelerate FTA talks**; diversify trade'],
            ['Climate resilience', 'Build sea-level rise and flooding into airports, ports, hospitals and water systems; solar, battery storage and efficiency to cut imported-fuel dependence'],
            ['People-to-people', 'Sustain Indian tourist flows while helping the Maldives diversify markets; use **Project Mausam** and shared Indian Ocean heritage'],
        ]),
        teacher('Class slide stress: “Conclusion” (slide 42)', '**Maldives is vital because of its strategic location, not size. India should combine security cooperation with respect for sovereignty.** The handout adds maritime safety and climate resilience under MAHASAGAR.'),
    ], label='Class + handout'))

    # ---------------------------------------------------------------- 14 compare
    secs.append(Sec('Eight neighbours side by side', [
        p('Built from the tables above, so you can answer a theme question with examples from several neighbours at once.'),
        tbl('One phrase each (from the slides)', ['Neighbour', 'The phrase', 'What it means'], [
            ['Pakistan', 'Structural rivalry', 'Credible deterrence + escalation control + limited functional engagement'],
            ['Afghanistan', 'Engagement without endorsement', 'Contact with the Taliban authorities, no formal recognition'],
            ['Bangladesh', 'Strategic reset', 'From “Sonali Adhyay” to transition, water and China issues'],
            ['Nepal', 'Roti-Beti and open border', 'Closeness that also breeds mistrust'],
            ['Bhutan', 'Bharat for Bhutan, Bhutan for Bharat', 'Most stable partnership; move beyond hydropower'],
            ['Myanmar', 'Calibrated engagement', 'Balance values, security and connectivity'],
            ['Sri Lanka', 'Crisis assistance to structured connectivity', 'Close but politically sensitive'],
            ['Maldives', 'Location, not size', 'From “India Out” to cautious reset'],
        ]),
        tbl('Founding treaties and agreements', ['Year', 'Treaty or agreement', 'With'], [
            ['1949; 2007', 'Friendship Treaty; revised Treaty of Friendship', 'Bhutan'],
            ['1950', 'Treaty of Peace and Friendship', 'Nepal'],
            ['1950', 'Treaty of Friendship', 'Afghanistan'],
            ['1951', 'Treaty of Friendship', 'Myanmar'],
            ['1960', 'Indus Waters Treaty', 'Pakistan'],
            ['1972', 'Shimla Agreement; Friendship Treaty', 'Pakistan; Bangladesh'],
            ['1974 and 1976', 'Maritime agreements (Katchatheevu; fishing)', 'Sri Lanka'],
            ['1976', 'Maritime Boundary Agreement (slide says 1979)', 'Maldives'],
            ['1987', 'Indo-Sri Lanka Accord', 'Sri Lanka'],
            ['1996', 'Ganga Water Treaty; Mahakali Treaty', 'Bangladesh; Nepal'],
            ['2011', 'Strategic Partnership Agreement', 'Afghanistan'],
            ['2015', 'Land Boundary Agreement', 'Bangladesh'],
            ['2024', 'Comprehensive Economic and Maritime Security Partnership', 'Maldives'],
        ]),
        tbl('Operations: which one, where, when', ['Operation', 'Year', 'What'], [
            ['Meghdoot', '1984', 'Siachen (Pakistan)'],
            ['Cactus', '1988', 'Maldives'],
            ['All Clear', '2003', 'Security cooperation with Bhutan'],
            ['Neer', '2014', 'Malé water crisis'],
            ['Maitri', '2015', 'Nepal earthquake'],
            ['Devi Shakti', '2021', 'Evacuation from Afghanistan'],
            ['Brahma', '2025', 'Myanmar earthquake (March)'],
            ['Sindoor', '2025', 'After the Pahalgam attack (Pakistan)'],
            ['Sagar Bandhu', '2025', 'Cyclone Ditwah relief, Sri Lanka (November)'],
        ]),
        tbl('Exercises', ['Neighbour', 'Exercises'], [
            ['Bangladesh', 'SAMPRITI; coordinated naval patrols'],
            ['Nepal', 'Surya Kiran'],
            ['Sri Lanka', 'Mitra Shakti (army), SLINEX (navy)'],
            ['Maldives', 'Ekuverin, Ekatha; Dosti (with Sri Lanka)'],
        ]),
        tbl('China’s footprint, neighbour by neighbour', ['Neighbour', 'What the material names'], [
            ['Pakistan', 'CPEC through PoK; Gwadar; weapons, drones, military technology'],
            ['Afghanistan', 'Diplomacy, infrastructure, mining (Mes Aynak copper), security contacts'],
            ['Bangladesh', 'Infrastructure and defence cooperation; submarine facilities'],
            ['Nepal', 'Framework for Belt and Road Cooperation (December 2024)'],
            ['Bhutan', 'Boundary negotiations; Doklam'],
            ['Myanmar', 'Kyaukphyu deep-water port; conflict mediation'],
            ['Sri Lanka', 'Hambantota'],
            ['Maldives', 'Research vessel (2024); China-Maldives FTA (January 2025)'],
        ], desc='This table is the evidence for the Mains 2026 question on the BRI in South Asia (skeleton in Chapter 2).'),
        tbl('Trade and borders: the numbers', ['Neighbour', 'Trade', 'Border or other number'], [
            ['Pakistan', 'Very limited since 2019', 'Attari ICP closed after Pahalgam'],
            ['Afghanistan', 'US$907.85 million (FY 2025-26)', 'No direct land route'],
            ['Bangladesh', 'US$14.01 billion (FY 2023-24)', '4,096 km: India’s longest land border; 864.482 km unfenced'],
            ['Nepal', 'US$9.39 billion (2025-26)', 'Open border; 82% of Nepal’s exports go to India'],
            ['Bhutan', '₹12,669 crore (2024)', 'India is about 80% of Bhutan’s trade'],
            ['Myanmar', 'US$2.15 billion (2024-25)', '1,643 km border'],
            ['Sri Lanka', 'US$7.18 billion (FY 2025-26)', 'India exports 5.5, imports 1.66'],
            ['Maldives', 'US$771.76 million (FY 2025-26)', 'About 60,000 Indians live there'],
        ]),
        tbl('Rivers and power', ['Neighbour', 'Arrangement', 'Problem'], [
            ['Pakistan', 'Indus Waters Treaty (1960)', 'In abeyance since April 2025; Kishanganga, Ratle'],
            ['Bangladesh', 'Ganga Treaty (1996); Kushiyara (2022); Joint Rivers Commission, 54 rivers', 'Treaty expires December 2026; Teesta unresolved since 2011'],
            ['Nepal', 'Koshi (1954), Gandak (1959), Mahakali (1996); 10,000 MW export target', 'Pancheshwar has no agreed project report'],
            ['Bhutan', 'Five projects, 3,156 MW; two-way power trade', 'Punatsangchhu-I delay; debt share'],
        ]),
        tbl('Digital payments', ['Neighbour', 'Link'], [
            ['Nepal', 'UPI-NPI linkage'],
            ['Bhutan', 'RuPay; UPI through Bhutan’s national QR system'],
            ['Sri Lanka', 'UPI QR payments (February 2024)'],
            ['Maldives', 'RuPay; Favara-UPI integration (July 2026)'],
        ]),
    ], label='Built from this chapter'))
    return secs


MAP = ('India and its neighbourhood', [
    ('Policy', [('Core', 'Neighbourhood First'), ('Gujral 1996', 'non-reciprocity'), ('Challenges', 'China; trust deficit; delivery'), ('Platforms', 'BIMSTEC, BBIN, IORA')]),
    ('Pakistan', [('Frame', 'deterrence + control + limited ties'), ('Disputes', 'J&K, Siachen, Sir Creek'), ('Water', 'IWT 1960; abeyance 2025'), ('2025', 'Pahalgam; Op Sindoor')]),
    ('Afghanistan', [('Frame', 'engagement, no recognition'), ('Route', 'Chabahar-Zaranj-Delaram'), ('Red line', 'no terror from Afghan soil')]),
    ('Bangladesh', [('Frame', 'strategic reset'), ('Border', '4,096 km; LBA 2015'), ('Water', 'Ganga 1996; Teesta'), ('Friction', 'transition; trade curbs')]),
    ('Nepal', [('Frame', 'Roti-Beti; open border'), ('Dispute', 'Kalapani-Lipulekh'), ('Energy', '10,000 MW export'), ('Sore points', '1950 Treaty; Agnipath')]),
    ('Bhutan', [('Frame', 'B4B; 2007 Treaty'), ('Hydro', '3,156 MW; Punatsangchhu'), ('Watch', 'Doklam; Gelephu')]),
    ('Myanmar', [('Frame', 'calibrated engagement'), ('Links', 'Kaladan; Trilateral Highway'), ('Border', '1,643 km; FMR'), ('China', 'Kyaukphyu')]),
    ('Sri Lanka', [('Frame', 'crisis aid to connectivity'), ('Tamil issue', '13th Amendment'), ('Fisheries', 'Katchatheevu 1974'), ('China', 'Hambantota')]),
    ('Maldives', [('Frame', 'location, not size'), ('Arc', 'India Out to reset'), ('Tools', 'swap; Greater Malé; CSC')]),
])

TIMELINE = [
    ('1816', 'Treaty of Sugauli: the India-Nepal boundary framework (slide)', False),
    ('1885', 'Myanmar annexed into British India', False),
    ('1947-48', 'Partition; J&K accession and the first India-Pakistan war', True),
    ('1948', 'Sri Lanka and Myanmar become independent', False),
    ('1949', 'India-Bhutan Friendship Treaty', False),
    ('1950', 'Treaty of Peace and Friendship with Nepal; Treaty of Friendship with Afghanistan', True),
    ('1951', 'Treaty of Friendship with Myanmar', False),
    ('1954, 1959', 'Koshi and Gandak agreements with Nepal', False),
    ('1960', 'Indus Waters Treaty (19 September)', True),
    ('1962, 1965', 'Wars with China and Pakistan: security recalibration', False),
    ('1971-72', 'Bangladesh Liberation War; Shimla Agreement; India-Bangladesh Friendship Treaty', True),
    ('1974, 1976', 'Maritime agreements with Sri Lanka (Katchatheevu; fishing)', True),
    ('1976', 'Maritime Boundary Agreement with the Maldives (handout; slide says 1979)', False),
    ('1984', 'Operation Meghdoot: Siachen', False),
    ('1985', 'SAARC', False),
    ('1987', 'Indo-Sri Lanka Accord; Rajiv Gandhi visits Myanmar', False),
    ('1988', 'Operation Cactus (Maldives); India-Pakistan agreement on nuclear installations', True),
    ('1989', 'India-Nepal trade-transit crisis', False),
    ('1991', 'Look East Policy', False),
    ('1996', 'Gujral Doctrine; Ganga Water Treaty; Mahakali Treaty', True),
    ('1997', 'BIMSTEC and IORA established', False),
    ('1998-99', 'Nuclear tests; Lahore; Kargil', False),
    ('2003', 'LoC ceasefire; Operation All Clear (Bhutan)', False),
    ('2004', 'Tsunami assistance to the Maldives', False),
    ('2007', 'India-Bhutan Treaty of Friendship (revised)', True),
    ('2008', 'Mumbai attacks; India-Pakistan Consular Access Agreement', False),
    ('2011', 'India-Afghanistan Strategic Partnership Agreement; Teesta draft understanding', False),
    ('2014', 'Neighbourhood First; maritime boundary settlement with Bangladesh; Operation Neer', False),
    ('2015', 'Land Boundary Agreement (111 and 51 enclaves); Operation Maitri; Madhesi crisis', True),
    ('2016, 2019', 'Surgical strikes; Balakot airstrikes; Kartarpur Corridor opens (2019)', False),
    ('2017', 'Doklam standoff', False),
    ('2020', 'Nepal’s new map: Kalapani, Lipulekh, Limpiyadhura', False),
    ('2021', 'Taliban takeover and Operation Devi Shakti; Myanmar coup; DGMOs reaffirm the ceasefire', True),
    ('2022', 'About US$4 billion for Sri Lanka’s crisis; Kushiyara agreement; India-Bhutan satellite', True),
    ('2023', 'Muizzu elected on “India Out”; first Indian cargo at Sittwe', False),
    ('2024', 'Sheikh Hasina’s exit (August); Maldives reset and partnership (October); Nepal-China BRI framework (December); Chabahar terminal arrangement', True),
    ('2025', 'Pahalgam attack, Operation Sindoor, IWT in abeyance; Operation Brahma (March); Operation Sagar Bandhu (November)', True),
    ('2026', 'Bangladesh renews extradition request (August); Favara-UPI live (July); Ganga Treaty expires (December)', True),
]

LINKS = [
    ('Chapter 2: India-China', 'China is listed as a neighbour here but is covered in Chapter 2. The “String of Pearls” and China-Pakistan nexus boxes there are this chapter’s China column.'),
    ('Chapter 2: Mains 2026 BRI question', 'The skeleton is in Chapter 2. The “China’s footprint” table in section 14 here gives it eight examples.'),
    ('Chapter 1: instruments', 'SAGAR and MAHASAGAR, the Diamond Necklace (Chabahar, Sabang) and “net security provider” are the tools; this chapter shows them in use.'),
    ('Chapter 1: determinant 3 (geography)', 'Pakistan blocks land access to Afghanistan and Central Asia, so Chabahar matters: explained here under Afghanistan.'),
    ('Inside the chapter: rivers', 'Indus (Pakistan), Ganga and Teesta (Bangladesh), Mahakali (Nepal), hydropower (Bhutan): one water answer, four examples.'),
    ('Inside the chapter: first responder', 'Cactus, Neer, Maitri, Devi Shakti, Brahma, Sagar Bandhu and the 2022 Sri Lanka package build one “first responder” paragraph.'),
    ('Inside the chapter: domestic politics', 'Teesta (West Bengal), Katchatheevu (Tamil Nadu), “India Out” (Maldives), the 2013 subsidy row (Bhutan), the Madhesi protests (Nepal).'),
    ('Syllabus: groupings', 'SAARC, BIMSTEC, BBIN, IORA, the Colombo Security Conclave and Mekong-Ganga Cooperation are named here and will return in the groupings chapter.'),
]

RECALL = [
    '**Policy:** Neighbourhood First = physical, digital, people-to-people connectivity, trade and commerce. Gujral Doctrine (1996) = non-reciprocity, non-interference, sovereignty, peaceful dispute resolution.',
    '**Eight challenges:** instability, security, China, trust deficit (“Big Brother”), weak integration, domestic politics (Teesta), refugees, climate (54 rivers).',
    '**Eight phases:** imperial security; Partition; idealism; security recalibration (1962, 1965); regional assertiveness (1971, 1987, 1988; SAARC 1985); economic regionalism (1991, 1996); multilateral regionalism (BIMSTEC, IORA 1997); proactive diplomacy (2014).',
    '**Pakistan:** deterrence + escalation control + limited engagement. J&K, Siachen (AGPL), Sir Creek. IWT 1960 in abeyance since April 2025. 1988 nuclear lists; 2008 consular access; 1974 Shrines Protocol; Kartarpur 2019 (suspended).',
    '**IWT:** western rivers Indus, Jhelum, Chenab (India’s limited rights); eastern Ravi, Beas, Sutlej (India’s exclusive rights); World Bank; 19 September 1960.',
    '**Afghanistan:** engagement without recognition. Parliament, Friendship (Salma) Dam, Zaranj-Delaram. Chabahar, Shahid Beheshti (2024). UNSC 2593. ISIL-K. Mes Aynak. Operation Devi Shakti.',
    '**Bangladesh:** strategic reset. 4,096 km; LBA 2015 (111 and 51). Trade US$14.01 bn. Ganga Treaty 1996 expires December 2026; Teesta (2011 draft); Kushiyara 153 cusecs; 54 rivers. Hasina exit August 2024.',
    '**Nepal:** Roti-Beti; HIT formula. 1950 Treaty; EPG 2018. Kalapani-Lipulekh-Limpiyadhura (2020 map). 10,000 MW; Arun-III. Koshi 1954, Gandak 1959, Mahakali 1996. Agnipath and the 1947 Tripartite Agreement. BRI framework December 2024.',
    '**Bhutan:** B4B; 1949 and 2007 treaties. 3,156 MW; Punatsangchhu-II done (2025), Punatsangchhu-I delayed. ₹10,000 crore for the 13th Plan. Gelephu. Doklam 2017. BBIN MVA not ratified. 2013 subsidy row.',
    '**Myanmar:** calibrated engagement. 1,643 km; FMR. Kaladan (Kolkata-Sittwe-Mizoram); Trilateral Highway. Kyaukphyu. Operation Brahma 2025. Rupee-Kyat (May 2024).',
    '**Sri Lanka:** about US$4 bn in 2022. 13th Amendment. Katchatheevu 1974; fishing 1976; bottom trawling. Sampur, Trincomalee hub, HVDC MoU. Operation Sagar Bandhu. Hambantota.',
    '**Maldives:** location, not size. Cactus 1988, tsunami 2004, Neer 2014. India Out 2023; civilians replace troops 2024; partnership October 2024. Swap US$400 mn + ₹30 bn. Greater Malé US$500 mn. China-Maldives FTA January 2025.',
    '**Closing line:** trust rather than dependence; less announcement, more delivery.',
]

TRAPS = [
    ('IWT: “in abeyance” is not “terminated”', 'India placed the treaty in abeyance after the April 2025 Pahalgam attack; Pakistan rejects that position. Rule: write “in abeyance”, and add that flood-information channels should continue.'),
    ('Western versus eastern rivers', 'Western: Indus, Jhelum, Chenab (India has limited rights). Eastern: Ravi, Beas, Sutlej (India’s exclusive rights). Rule: I-J-C is west, R-B-S is east.'),
    ('Two treaties with Bhutan', '1949 created the framework; 2007 modernised it and recognised Bhutan’s greater foreign-policy autonomy. Rule: ties today are “governed by the 2007 Treaty”.'),
    ('Punatsangchhu-I and II', 'II (1,020 MW) was completed in 2025. I (1,200 MW) is the delayed one. Rule: II is done, I is stuck.'),
    ('Planned is not operating', 'The Kokrajhar-Gelephu and Banarhat-Samtse rail links are planned (September 2025 MoU). The India-Sri Lanka power interconnection is an MoU. Kaladan is unfinished. Rule: say “proposed” or “planned”.'),
    ('Engagement is not recognition', 'India has a Technical Mission in Kabul but has not recognised the Taliban government. Rule: “engagement without recognition”.'),
    ('Katchatheevu: 1974 versus 1976', '1974 placed the island on Sri Lanka’s side. 1976 restricted fishing in each other’s waters. Rule: 1974 island, 1976 fishing.'),
    ('Slides and handout differ: Maldives boundary', 'Handout 1976; slide 1979. Rule: use the handout’s 1976 and check class notes.'),
    ('Slides and handout differ: Sri Lanka FTA', 'Handout “2000 ISFTA”; slide “1998”. Rule: name the agreement; check class notes before giving a year.'),
    ('Kyaukpyu or Kyaukphyu', 'The handout spells the Myanmar port both ways. Rule: either spelling is the same China-backed deep-water port.'),
    ('SAGAR, MAHASAGAR, Sagar Bandhu', 'SAGAR and MAHASAGAR are policy visions. Operation Sagar Bandhu is the 2025 cyclone relief for Sri Lanka. Slide 35 writes “SAGAR and maritime security” for 2025-26. Rule: vision versus operation.'),
    ('Operation Maitri and Vaccine Maitri', 'Operation Maitri: Nepal earthquake, 2015. Vaccine Maitri: COVID-19 vaccines (Bhutan was first). Rule: check the noun before “Maitri”.'),
    ('4,096 km and 1,643 km', 'Bangladesh is India’s longest land border (4,096 km; the handout also prints 4,096.7). Myanmar is 1,643 km. Rule: do not swap them.'),
    ('The Nepal “GLOF”', 'The handout calls the 2026 Nepal flood a GLOF. The August 2026 current-affairs magazine describes a glacier and rock collapse that dammed a river and then breached. Rule: “glacier-related flash flood” is safe.'),
]

MCQ = [
    ('The Gujral Doctrine (1996), as described in the handout, emphasised:', ['Reciprocity and strict conditionality', 'Non-reciprocity, non-interference, respect for sovereignty and peaceful dispute resolution', 'Military alliances with neighbours', 'A common South Asian currency'], 1, 'Handout p. 3. The way forward pairs it with Neighbourhood First.'),
    ('BIMSTEC and IORA were both established in:', ['1985', '1991', '1997', '2014'], 2, 'Both in 1997 (“multilateral regionalism”). SAARC is 1985.'),
    ('Under the Indus Waters Treaty, the “western rivers” are:', ['Ravi, Beas, Sutlej', 'Indus, Jhelum, Chenab', 'Indus, Ravi, Sutlej', 'Jhelum, Chenab, Beas'], 1, 'Western: Indus, Jhelum, Chenab (India has limited rights). Eastern: Ravi, Beas, Sutlej (India’s exclusive rights).'),
    ('Under which agreement do India and Pakistan exchange lists of nuclear installations every year?', ['Shimla Agreement, 1972', 'The 1988 Agreement', 'Tashkent Agreement', 'Consular Access Agreement, 2008'], 1, 'The 1988 Agreement. The 2008 agreement covers prisoner lists, exchanged twice a year.'),
    ('India’s position on Siachen in the handout is that:', ['It should be demilitarised at once', 'The Actual Ground Position Line must be authenticated before demilitarisation', 'It should go to third-party arbitration', 'It is part of the Sir Creek dispute'], 1, 'India seeks authentication of the AGPL first. India rejects third-party mediation on Kashmir.'),
    ('Which phrase does the material use for India’s approach to the Taliban authorities?', ['Recognition with conditions', 'Engagement without endorsement (or recognition)', 'Complete disengagement', 'Strategic alliance'], 1, 'Slide 13: “engagement without endorsement”; the conclusion says “engagement without recognition”.'),
    ('The 2015 Land Boundary Agreement with Bangladesh led to the exchange of:', ['51 Indian and 111 Bangladeshi enclaves', '111 Indian and 51 Bangladeshi enclaves', '54 enclaves each', '162 Indian enclaves only'], 1, '111 Indian and 51 Bangladeshi enclaves. 54 is the number of shared rivers.'),
    ('The 1996 Ganga Water Sharing Treaty is due to expire in:', ['December 2025', 'December 2026', 'December 2030', 'It has no expiry'], 1, 'December 2026. Teesta remains unresolved despite a draft understanding dating to 2011.'),
    ('Nepal opposed India’s Agnipath Scheme on the ground that it violated the:', ['1950 Treaty of Peace and Friendship', '1947 Tripartite Agreement', '1996 Mahakali Treaty', 'Treaty of Sugauli'], 1, 'The 1947 Tripartite Agreement on Gorkha recruitment.'),
    ('Which statement about India-Bhutan hydropower is correct?', ['Punatsangchhu-I was completed in 2025', 'Punatsangchhu-II (1,020 MW) completed its final unit commissioning in 2025', 'Five projects total 10,000 MW', 'Bhutan only imports power from India'], 1, 'Punatsangchhu-II is complete; Punatsangchhu-I (1,200 MW) is delayed. Five projects total 3,156 MW. Power trade is two-way.'),
    ('The Kaladan Multi-Modal Transit Transport Project links:', ['Kolkata, Sittwe and Mizoram', 'Chennai, Yangon and Manipur', 'Kolkata, Chattogram and Tripura', 'Haldia, Kyaukphyu and Nagaland'], 0, 'Kolkata-Sittwe-Mizoram. Sittwe received its first Indian cargo in 2023; the full corridor is unfinished.'),
    ('Operation Brahma (2025) was India’s response to:', ['Cyclone Ditwah in Sri Lanka', 'An earthquake in Myanmar', 'A water crisis in Malé', 'An earthquake in Nepal'], 1, 'Myanmar earthquake, March 2025. Ditwah: Sagar Bandhu. Malé: Neer. Nepal: Maitri.'),
    ('The 13th Amendment to Sri Lanka’s Constitution provides for:', ['A presidential system', 'Provincial Councils', 'Tamil as the only official language', 'A federal second chamber'], 1, 'Provincial Councils. India seeks its meaningful implementation and Provincial Council elections.'),
    ('The 1974 India-Sri Lanka maritime agreement:', ['Gave India fishing rights in all Sri Lankan waters', 'Placed Katchatheevu on Sri Lanka’s side of the boundary', 'Created the Colombo Security Conclave', 'Banned bottom trawling'], 1, '1974 placed the island on Sri Lanka’s side; the 1976 agreement restricted fishing in each other’s waters.'),
    ('Which sequence is correct for the Maldives?', ['Operation Neer (1988), Operation Cactus (2014)', 'Operation Cactus (1988), tsunami aid (2004), Operation Neer (2014)', 'Tsunami aid (1988), Cactus (2004), Neer (2014)', 'Cactus (2014), Neer (2023)'], 1, 'Cactus 1988, tsunami 2004, Neer 2014: the “First Responder” record.'),
    ('In 2024 the Maldives declined to renew which agreement with India?', ['The currency-swap arrangement', 'The joint hydrographic survey agreement', 'The Maritime Boundary Agreement', 'The Greater Malé Connectivity Project'], 1, 'The hydrographic survey agreement, citing control over information about its waters.'),
    ('Which pair is correctly matched?', ['SAMPRITI: Nepal', 'Surya Kiran: Bangladesh', 'Mitra Shakti: Sri Lanka', 'Ekuverin: Bhutan'], 2, 'SAMPRITI: Bangladesh. Surya Kiran: Nepal. Mitra Shakti and SLINEX: Sri Lanka. Ekuverin and Ekatha: Maldives.'),
    ('Nepal signed a Framework for Belt and Road Cooperation with China in:', ['2017', '2020', 'December 2024', 'July 2026'], 2, 'December 2024. Nepal’s new map was 2020.'),
]

CARDS = [
    ('Neighbourhood First in one line?', 'Physical, digital and people-to-people connectivity, trade and commerce (slide 4).'),
    ('Gujral Doctrine?', '1996: non-reciprocity, non-interference, respect for sovereignty, peaceful dispute resolution.'),
    ('The slide’s core idea on geography?', 'Geography creates permanent interdependence; politics and security decide whether it becomes cooperation or friction.'),
    ('Eight challenges in the neighbourhood?', 'Instability, security threats, China, trust deficit, weak integration, domestic politics, refugees, climate.'),
    ('Which neighbours were “strategic buffers” before 1947?', 'Nepal, Bhutan, Afghanistan and Tibet. Myanmar was annexed into British India in 1885.'),
    ('1970s-80s “regional assertiveness”: three events?', 'Bangladesh Liberation War (1971), India-Sri Lanka Accord (1987), Operation Cactus (1988). SAARC came in 1985.'),
    ('Pakistan: the three-part frame?', 'Credible deterrence + escalation control + limited functional engagement.'),
    ('Three territorial disputes with Pakistan?', 'Jammu and Kashmir, Siachen (AGPL authentication), Sir Creek (maritime boundary, EEZ, fishing).'),
    ('IWT: status and rivers?', 'Signed 19 Sept 1960 with the World Bank; in abeyance since April 2025. West: Indus, Jhelum, Chenab. East: Ravi, Beas, Sutlej.'),
    ('Four India-Pakistan channels that survive?', '2003 LoC ceasefire and DGMO line; 1988 nuclear lists; 2008 consular access; 1974 Shrines Protocol (Kartarpur suspended).'),
    ('Stability-instability paradox?', 'Nuclear weapons prevent full-scale war, but lower-level conflict can continue below the nuclear threshold.'),
    ('After Pahalgam, what did India do on trade?', 'Closed the Attari Integrated Check Post and further restricted Pakistan-origin imports.'),
    ('India’s Afghanistan policy in one phrase?', 'Engagement without endorsement (recognition): Technical Mission in Kabul, no recognition of the Taliban government.'),
    ('India’s flagship projects in Afghanistan?', 'Parliament Building, Afghan-India Friendship (Salma) Dam, Zaranj-Delaram Road.'),
    ('Why Chabahar?', 'It gives Afghanistan sea access and India a route bypassing Pakistan. Shahid Beheshti Terminal: 2024 long-term arrangement.'),
    ('UNSC Resolution 2593?', 'Afghan territory must not be used to threaten or attack other countries.'),
    ('China in Afghanistan?', 'Diplomacy, infrastructure, mining (Mes Aynak copper) and security contacts.'),
    ('Bangladesh: border and enclaves?', '4,096 km, India’s longest land border; LBA 2015 exchanged 111 Indian and 51 Bangladeshi enclaves; 864.482 km unfenced.'),
    ('Bangladesh water: three facts?', 'Ganga Treaty 1996 expires Dec 2026; Teesta unresolved since a 2011 draft; Kushiyara 2022, 153 cusecs each. 54 shared rivers.'),
    ('Bangladesh connectivity?', 'Akhaura-Agartala rail; Chattogram and Mongla ports; Friendship Pipeline (1 MMT diesel); 40 MW Nepal power via India (Nov 2024).'),
    ('Trade frictions with Bangladesh in 2025?', 'Curbs on garments, some food and plastics; land-port restrictions; trans-shipment facility withdrawn (April 2025).'),
    ('Nepal: HIT formula?', 'Highways, I-ways, Trans-ways.'),
    ('Nepal boundary dispute?', 'Kalapani, Lipulekh, Limpiyadhura; Nepal’s 2020 map; India-China activity at Lipulekh adds a third party.'),
    ('Nepal water treaties?', 'Koshi (1954), Gandak (1959), Mahakali (1996). Pancheshwar still has no agreed project report.'),
    ('Nepal energy?', '2024 agreement: up to 10,000 MW export to India. SJVN: Arun-III (900 MW), Lower Arun (669 MW).'),
    ('Nepal’s two treaty grievances?', '1950 Treaty (EPG recommendations of 2018 unimplemented) and Agnipath versus the 1947 Tripartite Agreement.'),
    ('Bhutan: treaties and core idea?', '1949 Friendship Treaty; 2007 Treaty (more foreign-policy autonomy). “Bharat for Bhutan, Bhutan for Bharat”.'),
    ('Bhutan hydropower numbers?', 'Five projects, 3,156 MW. Punatsangchhu-II 1,020 MW done (2025); Punatsangchhu-I 1,200 MW delayed. Electricity is 12-15% of GDP.'),
    ('Bhutan divergence points?', 'Bhutan-China boundary talks and Doklam; BBIN MVA unratified; hydropower debt; 80% trade dependence; 2013 subsidy row.'),
    ('Operation All Clear?', '2003, security cooperation with Bhutan.'),
    ('Myanmar in one phrase?', 'Calibrated engagement: balance values, security and connectivity.'),
    ('Myanmar connectivity?', 'Kaladan (Kolkata-Sittwe-Mizoram; Sittwe’s first Indian cargo 2023; unfinished) and the India-Myanmar-Thailand Trilateral Highway.'),
    ('Myanmar border issues?', '1,643 km; insurgency, drugs (Death Triangle), arms; fencing and FMR limits opposed in Mizoram and by Naga groups; refugees.'),
    ('Sri Lanka 2022?', 'About US$4 billion in financing and supplies; India co-chaired the Official Creditor Committee.'),
    ('Sri Lanka: fisheries dispute in three facts?', 'Katchatheevu on Sri Lanka’s side (1974); fishing restricted (1976); bottom trawling; Delft Island firing (Jan 2025).'),
    ('Sri Lanka energy projects?', 'Sampur solar; HVDC interconnection MoU (April 2025); Trincomalee energy hub with the UAE. Adani exited Mannar and Pooneryn.'),
    ('Operation Sagar Bandhu?', 'Relief after Cyclone Ditwah (Nov 2025): over 1,058 tonnes; US$450 million recovery package.'),
    ('Maldives: First Responder record?', 'Operation Cactus (1988), tsunami (2004), Operation Neer (2014 Malé water crisis).'),
    ('Maldives: from India Out to reset?', 'Muizzu elected 2023; troops replaced by civilian staff 2024; Comprehensive Economic and Maritime Security Partnership (Oct 2024).'),
    ('Maldives: India’s economic tools?', 'RBI swap (US$400 mn + ₹30 bn); Greater Malé Connectivity (US$500 mn); Hanimaadhoo runway; RuPay and Favara-UPI; FTA talks.'),
    ('China in the Maldives?', 'Research vessel docking (2024); China-Maldives FTA in force January 2025.'),
    ('Closing line for any neighbourhood answer?', 'Combine the Gujral Doctrine’s non-reciprocity with Neighbourhood First’s connectivity, security and development: trust rather than dependence.'),
]

SKELETONS = [
    ('Mains 2024 (15m, 250w): importance of the Maldives; effect on India’s maritime security',
     'Intro: the Maldives matter for location, not size: they sit in the Central Indian Ocean near the sea lanes carrying India’s trade and energy.',
     ['Part 1, importance: sea lanes and energy flows; India as First Responder (Cactus 1988, tsunami 2004, Neer 2014); Comprehensive Economic and Maritime Security Partnership (October 2024).',
      'Part 1, economics: Greater Malé Connectivity Project (US$500 mn), Hanimaadhoo runway, currency swap (US$400 mn and ₹30 bn), RuPay and Favara-UPI.',
      'Part 2, security and stability: Ekuverin, Ekatha, Dosti; Colombo Security Conclave; shared concerns of radicalisation and crime.',
      'Part 2, international competition: “India Out” (2023-24); Chinese research vessel (2024); China-Maldives FTA (January 2025); hydrographic agreement not renewed; suspicion about the UTF Harbour.',
      'Way forward: sovereignty-sensitive engagement; clear rules for Indian-supported assets; operational decisions with Maldivian authorities; FTA; climate-resilient infrastructure.'],
     'Closing: combine security cooperation with respect for sovereignty, under MAHASAGAR.'),
    ('Mains 2022 (10m, 150w): India as an age-old friend in Sri Lanka’s crisis',
     'Intro: more than 2,500 years of cultural contact and close maritime proximity; in 2022 India acted as first responder.',
     ['What India did: about US$4 billion in emergency financing and supplies; co-chaired the Official Creditor Committee for debt restructuring; Vaccine Maitri before it.',
      'Why: Neighbourhood First and SAGAR/MAHASAGAR; stability in the Indian Ocean; China’s Hambantota presence.',
      'After the crisis: from assistance to connectivity (UPI, ferry, Kankesanthurai port, Sampur solar, Trincomalee hub).',
      'Limits to “age-old friend”: Tamil devolution (13th Amendment), fisheries and Katchatheevu, trade imbalance.'],
     'Closing: the friendship is proved in crisis but kept by delivery and sensitivity.'),
    ('Mains 2015 (12.5m, 200w): does Project Mausam have a strategic dimension?',
     'Intro: Project Mausam builds on shared Indian Ocean heritage. (**Thin notes:** the handout only names it, in the Maldives way forward. The August 2026 current-affairs magazine adds: maritime and cultural linkages across the Indian Ocean world; nodal agency IGNCA, with ASI and the National Museum.)',
     ['Cultural face: heritage and people-to-people links with Indian Ocean neighbours (Maldives, Sri Lanka).',
      'Strategic reading: culture supports MAHASAGAR and Neighbourhood First; it builds goodwill where China offers ports and loans (Hambantota, research vessels).',
      'Limits: soft power does not settle hard issues (“India Out”, fisheries); it needs delivery on projects.'],
     'Closing: cultural in form, strategic in effect, but only alongside connectivity and security cooperation. Add details from class notes.'),
    ('Mains 2015 (12.5m, 200w): can sport and culture generate India-Pakistan goodwill?',
     'Intro: relations are a structural, security-driven rivalry; yet humanitarian and religious channels continue.',
     ['Where soft power works: shared Punjabi, Sindhi and Sufi traditions; the 1974 Shrines Protocol; the Kartarpur Corridor (2019) as a people-to-people link.',
      'Where it stops: cross-border terrorism (Mumbai, Pathankot, Uri, Pulwama, Pahalgam) repeatedly broke dialogue; Kartarpur itself was suspended in 2025; the Pakistan Army’s dominant role limits civilian initiatives.',
      '“To what extent”: soft power can keep societies in contact and lower hostility, but cannot replace verifiable action on terror.',
      'Way forward: insulate pilgrims, prisoners, fishermen and medical cases from politics.'],
     'Closing: goodwill follows a terror-free environment; it cannot create one.'),
]
